### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by markalex2209**
Multiple minor improvements:
- Added a quick link to edit OSM element to reports and maps
- Moved miscellaneous analyzers and fetchers into a dedicated folder to clean up structure
- Updated projects and actions script to use .net8

### CODE REVIEW

**Comment by HellMapGoesCoding** [comment]
I'm sorry, but I cannot locally switch to .NET 8.0 at the moment due to the IDE and tooling I have set up that I cannot really change. I planned to switch at some point though. Is there something specific you are wanting from 8.0?

Theoretically, I think you can set the project framework to be "latest" or something to roll forward up to whatever the IDE is capable of, but I think I remember GitHub not liking not having an exact version or something like that, so it's not stored in the repo.

**Comment by markalex2209** [comment]
Hmmm....

I'm getting mixed signals here: you said you can switch to .Net 8.0, but merged full branch?

Regarding .Net version: I had to reinstall OS, recently and while was trying to download .Net SDK 7, microsoft said it's no longer supported, and that 8.0 is an LTS. After quick check I didn't see anything in project that required older version, so I submitted this change. If that is still a limitation from your side, please feel free to rollback my last to commits.

**Comment by HellMapGoesCoding** [comment]
Sorry for the confusion. I merged it to get the other changes so you don't have to redo/adjust the PR. I just undid the .NET stuff locally for now and I'll redo it when I can switch, so the commits are already available in history. I also made some changes to code myself in between, so I needed to adjust and test locally anyway.

I also adjusted the pencil being a bit too prominent when there are a lot of links/elements listed. It's one of the reasons why I hadn't added more of such things in reports - they eat up a lot of space and it becomes really difficult to quickly see things. So I think it's fine to have an edit link, but it should be less prominent than the element link itself, if you see what I mean.

pencil PENCIIIIIIL
pencil not so pencil

**Comment by markalex2209** [comment]
Oh, thanks for explanation.

Regarding pen image: I agree that yours look more appropriate.

**Pull request merged**
